packages:
  - packages/*
  - apps/*
ignoredBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - msw
  - sharp
  - workerd
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - prisma
shared-workspace-lockfile: true
