# This is a basic workflow to help you get started with Actions

name: BAREFEED-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test -- run --coverage
        env:
          CI: true

      # - name: Install dependencies
      #   run: npm ci
      # - name: Run tests
      #   run: npm test -- run --coverage
      #   env:
      #     CI: true
