name: Deploy - nullsweat-brochure

on:
  push:
    branches: [main]
    paths:
      - 'apps/nullsweat-brochure/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: 9ab0a868ac2600134d3bca1061e39272
        run: npx wrangler pages deploy apps/nullsweat-brochure --project-name=nullsweat-io
