name: Test2Docs Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -f Dockerfile.ci -t test2doc-ci .

      - name: Run Tests in Docker
        run: |
          docker run --rm \
            -e CI=true \
            test2doc-ci
  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         run_install: false
  #     - name: Node Setup
  #       uses: actions/setup-node@v4
  #       with:
  #         cache: pnpm
  #         node-version: "latest"
  #     - name: Install Dependencies
  #       run: pnpm install --frozen-lockfile
  #     - name: Install Playwright Dependencies
  #       run: pnpm playwright install --with-deps
  #     - name: Run Tests
  #       # uses: "./.github/actions/test"
  #       # with:
  #       #   app: "test2doc"
  #       run: pnpm run test:test2doc
  #       env:
  #         CI: true
  # # build:
  # #   needs: test
  # #   runs-on: ubuntu-latest
  # #   steps:
  # #     - name: Branch Checkout
  # #       uses: actions/checkout@v4
  # #     - name: Install pnpm
  # #       uses: pnpm/action-setup@v4
  # #       with:
  # #         run_install: false
  # #     - name: Node Setup
  # #       uses: actions/setup-node@v4
  # #       with:
  # #         cache: pnpm
  # #         node-version: "latest"
  # #         registry-url: "https://registry.npmjs.org"
  # #     - name: Install Dependencies
  # #       run: pnpm install
  # #     - name: Publish Package
  # #       run: pnpm publish:test2doc
  # #       env:
  # #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
